spring:
  application:
    name: "Kafka REST Proxy"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: "rest-proxy"
      compression-type: "snappy"
    consumer:
      enable-auto-commit: false
      client-id: "rest-proxy"
  jackson:
    generator:
      quote-field-names: true
    serialization:
      indent_output: false
logging:
  level:
    org.apache.kafka: WARN