spring:
  application:
    name: "Kafka REST Proxy"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
  jackson:
    generator:
      quote-field-names: true
    serialization:
      indent_output: false
logging:
  level:
    org.apache.kafka: WARN