spring:
  application:
    name: "Kafka REST Proxy"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: "rest-proxy"
      compression-type: "snappy"
      acks: "all"
      properties:
        buffer.memory: 134217728
        max.request.size: 67108864
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
  jackson:
    generator:
      quote-field-names: true
    serialization:
      indent_output: false
logging:
  level:
    org.apache.kafka: WARN